[GLOBAL]
pants_version = "2.16.0"
backend_packages.add = [
  "pants.backend.python",
]

[python]
interpreter_constraints = ["CPython==3.11.*"]
enable_resolves = true
resolves = { python-default = "python-default.lock"}
resolves_to_constraints_file = { python-default = "constraints.txt" }

[anonymous-telemetry]
enabled = false
